customers = [
    {"customer_id": "CUST001", "name": "Alice Smith", "email": "alice.smith@example.com"},
    {"customer_id": "CUST002", "name": "Bob Johnson", "email": "bjohnson@example.com"},
    {"customer_id": "CUST003", "name": "Charlie Davis", "email": "cdavis@example.com"},
    {"customer_id": "CUST004", "name": "Diana Prince", "email": "dprince@example.com"},
    {"customer_id": "CUST005", "name": "Edward Norton", "email": "enorton@example.com"},
    {"customer_id": "CUST006", "name": "Fiona Gallagher", "email": "fgallagher@example.com"},
    {"customer_id": "CUST007", "name": "George Miller", "email": "gmiller@example.com"},
    {"customer_id": "CUST008", "name": "Hannah Abbott", "email": "habbott@example.com"},
    {"customer_id": "CUST009", "name": "Ian Malcolm", "email": "imalcolm@example.com"},
    {"customer_id": "CUST010", "name": "Julia Roberts", "email": "jroberts@example.com"},
    {"customer_id": "CUST011", "name": "Kevin Hart", "email": "khart@example.com"},
    {"customer_id": "CUST012", "name": "Laura Palmer", "email": "lpalmer@example.com"},
    {"customer_id": "CUST013", "name": "Michael Scott", "email": "mscott@example.com"},
    {"customer_id": "CUST014", "name": "Nina Simone", "email": "nsimone@example.com"},
    {"customer_id": "CUST015", "name": "Oscar Isaac", "email": "oisaac@example.com"}
]

orders = [
    {"order_id": "ORD001", "customer_id": "CUST001", "product_name": "Premium Leather Jacket", "price": 550.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD002", "customer_id": "CUST002", "product_name": "Monthly Coffee Blend", "price": 25.00, "is_refundable": False, "is_final_sale": False, "is_delivered": True, "is_subscription": True},
    {"order_id": "ORD003", "customer_id": "CUST003", "product_name": "Clearance Winter Boots", "price": 45.99, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD004", "customer_id": "CUST004", "product_name": "Smartphone Pro Max", "price": 1099.00, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD005", "customer_id": "CUST005", "product_name": "Wireless Noise-Canceling Headphones", "price": 299.99, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD006", "customer_id": "CUST006", "product_name": "Vitamin C Serum (Monthly)", "price": 35.00, "is_refundable": False, "is_final_sale": False, "is_delivered": False, "is_subscription": True},
    {"order_id": "ORD007", "customer_id": "CUST007", "product_name": "4K Ultra HD Smart TV", "price": 850.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD008", "customer_id": "CUST008", "product_name": "Sample Perfume Set - Final Sale", "price": 15.00, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD009", "customer_id": "CUST009", "product_name": "Ergonomic Office Chair", "price": 350.00, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD010", "customer_id": "CUST010", "product_name": "Gaming Laptop Xtreme", "price": 1800.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD011", "customer_id": "CUST011", "product_name": "Monthly Snack Box", "price": 40.00, "is_refundable": False, "is_final_sale": False, "is_delivered": True, "is_subscription": True},
    {"order_id": "ORD012", "customer_id": "CUST012", "product_name": "Designer Sunglasses", "price": 220.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD013", "customer_id": "CUST013", "product_name": "Graphic T-Shirt (Clearance)", "price": 12.99, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD014", "customer_id": "CUST014", "product_name": "Smart Home Hub", "price": 129.99, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD015", "customer_id": "CUST015", "product_name": "Digital Camera Bundle", "price": 650.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD016", "customer_id": "CUST001", "product_name": "Monthly Protein Powder", "price": 55.00, "is_refundable": False, "is_final_sale": False, "is_delivered": True, "is_subscription": True},
    {"order_id": "ORD017", "customer_id": "CUST002", "product_name": "Running Shoes", "price": 130.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD018", "customer_id": "CUST003", "product_name": "Custom Engraved Watch", "price": 199.99, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD019", "customer_id": "CUST004", "product_name": "Robot Vacuum Cleaner", "price": 450.00, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD020", "customer_id": "CUST005", "product_name": "High-End Espresso Machine", "price": 1200.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD021", "customer_id": "CUST006", "product_name": "Yoga Mat", "price": 28.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD022", "customer_id": "CUST007", "product_name": "Cloud Storage (Annual)", "price": 99.00, "is_refundable": False, "is_final_sale": False, "is_delivered": True, "is_subscription": True},
    {"order_id": "ORD023", "customer_id": "CUST008", "product_name": "Electric Guitar", "price": 599.00, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD024", "customer_id": "CUST009", "product_name": "Mystery Tech Box", "price": 50.00, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD025", "customer_id": "CUST010", "product_name": "Silk Pillowcase Set", "price": 65.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD026", "customer_id": "CUST011", "product_name": "Electric Standing Desk", "price": 510.00, "is_refundable": True, "is_final_sale": False, "is_delivered": False, "is_subscription": False},
    {"order_id": "ORD027", "customer_id": "CUST012", "product_name": "Monthly Book Club", "price": 20.00, "is_refundable": False, "is_final_sale": False, "is_delivered": True, "is_subscription": True},
    {"order_id": "ORD028", "customer_id": "CUST013", "product_name": "Winter Scarf (Clearance)", "price": 9.50, "is_refundable": False, "is_final_sale": True, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD029", "customer_id": "CUST014", "product_name": "Cast Iron Skillet", "price": 45.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False},
    {"order_id": "ORD030", "customer_id": "CUST015", "product_name": "Home Theater Sound System", "price": 750.00, "is_refundable": True, "is_final_sale": False, "is_delivered": True, "is_subscription": False}
]